clients/urls.py
from django.urls import path
from . import views

app_name = 'clients'

urlpatterns = [
	path("", views.index, name="index"),
	path('register', views.register, name="register"),
	path('search', views.search_view, name="search"),
	path('client/<int:client_id>/', views.client_details, name='client_details'),
	path('client/<int:client_id>/edit/', views.edit_client, name='edit_client'),
	path('client/<pk>/delete/', views.delete_client, name='delete'),
]

djangoProject9/urls.py
from django.contrib import admin
from django.urls import path, include
import pwa.urls

# url patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clients/', include('clients.urls')),
    path('', include('eccentric.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
]

eccentric/urls.py
from django.urls import path
from . import views

app_name = 'eccentric'

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),

]

eccentric/models.py
from django.db import models

# Create your models here.

eccentric/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        widgets = {
            "username": forms.TextInput(attrs={
                'class': 'input-text',
                'id': 'username',
            }),
            "password1": forms.PasswordInput(attrs={
                'class': 'input-text',
                'id': 'password1',
            }),
            "password2": forms.PasswordInput(attrs={
                'class': 'input-text',
                'id': 'password2',
            }),
            'email': forms.EmailInput(attrs={'class': 'input-text', 'id': 'email',}),
        }


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

eccentric/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from .forms import CustomUserCreationForm, CustomAuthenticationForm
from django.contrib.auth.forms import AuthenticationForm

from django.conf import settings
from django.templatetags.static import static
import os

# Create your views here.

def home(request):
    return render(request, 'eccentric/home.html')


def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('clients:index')
    else:
        form = CustomUserCreationForm()
    return render(request, 'eccentric/register.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        print('post')
        form = CustomAuthenticationForm(request, data=request.POST)
        if form.is_valid():

            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            # print(password, username)
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('clients:index')
            else:
                print('not user')
    else:
        form = CustomAuthenticationForm()
    return render(request, 'eccentric/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('eccentric:home')

eccentric/templates/eccentric/home.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width">
	{% load static %}
	<link rel="icon" type="image/png" href="{% static 'iconfavicon.png' %}">
	<title>Sinsio</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<link href="{% static 'eccentric/home.css' %}" rel="stylesheet">
	<link href="{% static 'manifest.json' %}" rel="manifest">
	<script defer src="{% static 'js/main.js' %}"></script>
	<!-- <link rel="stylesheet" href="{% static 'clients/index.css' %}"> -->

</head>
<body>
	<nav id="home-nav">
		<div class="title">
			<form action="{% url 'eccentric:home' %}">
				<button class="title home" type="submit">Sinsio</button>
			</form>
		</div>
		<div class="buttons">
			<form action="{% url 'eccentric:register' %}">
				<button class="register" type="submit">Register</button>
			</form>
			<form action="{% url 'eccentric:login' %}" method="GET">
				<button class="login" type="submit">Login</button>
			</form>
		</div>
	</nav>
	<br>
	<section id="home">
	{% block home %}
		<div class="heading">
			Your Clients on Your Palm
		</div>
		<br>
		<br>
		<div class="landing-page">
		<div class="organize">
			Organize
		</div>
		<div class="arrow-down">
			<img src="{% static 'doublearrow.svg' %}">
		</div>
		<div class="manage">
			Manage
		</div>
		<div class="arrow-down">
			<img src="{% static 'doublearrow.svg' %}">
		</div>
		<div class="grow">
			Grow
		</div>
		<br>
		<div>
			<img id="growth" src="{% static 'growth.png' %}">
		</div>
	</div>
		<form class="contact-us">
			<a id="send-message" href="https://wa.me/254706088217?" target="_blank">
				<img id="whatsapp" src="{% static 'eccentric/svg/whatsapp-chat.svg' %}">
			</a>
		</form>
	{% endblock %}
	</section>

	<footer>
		<form action="{% url 'clients:index' %}" method="POST">
			{% csrf_token %}
			<button type="submit" class="clients">
				<img id="clients-group" src="{% static 'eccentric/svg/clients_group.svg' %}">
			</button>
		</form>

		<form action="{% url 'clients:search' %}" method="GET">
			{% csrf_token %}
			<button type="submit" class="search">
				<img id="search-client" src="{% static 'eccentric/svg/search.svg' %}">
			</button>
		</form>

		<button class="notify">
			<img id="notify" src="{% static 'eccentric/svg/notify.svg' %}">
		</button>
	</footer>
</body>
</html>

eccentric/templates/eccentric/login.html
{% extends 'eccentric/home.html' %}
{% block home %}

<form id="login-form" method="post" action="{% url 'eccentric:login' %}">
	<div class="title">Login</div>
    {% csrf_token %}
	<div>
		<label>
			User Name <br>
			{{ form.username }}
		</label>
	</div>
	<br>
    <div>
		<label>
			Password <br>
			{{ form.password }}
		</label>
	</div>
	<br>
    <div>
		<button id="login-button" class="form-submit" type="submit">Login</button>
	</div>
</form>
{% endblock %}

eccentric/templates/eccentric/loogedin.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Logged In</title>
</head>
<body>
<h1>LOGGED IN</h1>

</body>
</html>

eccentric/templates/eccentric/register.html
{% extends 'eccentric/home.html' %}

{% block home %}

<form id="sign-up-form" method="post" action="{% url 'eccentric:register' %}">
	<div class="title">Register</div>
    {% csrf_token %}
    <div>
		<label> User Name<br>
			{{ form.username }}
		</label>
	</div>
	<div>
		<label> Email<br>
			{{ form.email }}
		</label>
	</div>
	<div>
		<label> Password<br>
			{{ form.password1 }}
		</label>
	</div>
	<div>
		<label> Confirm Password <br>
			{{ form.password2 }}
		</label>
	</div>
	<br>
    <button id="signup" type="submit">Register</button>
</form>
{% endblock %}