clients/urls.py
from django.urls import path
from . import views

app_name = 'clients'

urlpatterns = [
	path("", views.index, name="index"),
	path('register', views.register, name="register"),
	path('search', views.search_view, name="search"),
	path('client/<int:client_id>/', views.client_details, name='client_details'),
	path('client/<int:client_id>/edit/', views.edit_client, name='edit_client'),
	path('client/<pk>/delete/', views.delete_client, name='delete'),
]

djangoProject9/urls.py
from django.contrib import admin
from django.urls import path, include
import pwa.urls

# url patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clients/', include('clients.urls')),
    path('', include('eccentric.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
]

eccentric/urls.py
from django.urls import path
from . import views

app_name = 'eccentric'

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),

]

clients/models.py
from django.db import models
from datetime import date
from django.contrib.auth.models import User

# Create your models here.

class Client(models.Model):
	name = models.CharField(max_length=50)
	policy_number = models.CharField(max_length=50)
	registration_number = models.CharField(max_length=50)
	start_date = models.DateField(null=True)
	end_date = models.DateField(null=True)
	renewal_date = models.DateField(null=True)
	amount = models.DecimalField(max_digits=10, decimal_places=2)
	phone_number = models.CharField(max_length=20, null=True, blank=True)
	created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, default=None, blank=True)


	def __str__(self):
		return f"{self.name}, {self.policy_number}, {self.registration_number}, " \
			   f"{self.start_date}, {self.end_date}, {self.amount}, {self.phone_number}"

clients/forms.py
from django import forms
from clients.models import Client
from django.contrib.auth.models import User

# instantiated form for editing the client model and the required fields
class ClientForm(forms.ModelForm):

	class Meta:
		model = Client

		fields = [
			"id", "name", "policy_number", "registration_number", "phone_number",
			"start_date", "end_date", "renewal_date", "amount", 'created_by',
	  	]

		#adding CSS classes and IDs for forms fields for use in front end
		widgets = {
			
			"name": forms.TextInput(attrs={
				'class': 'input-text',
				'id': 'client-name',
			}),
			"policy_number": forms.TextInput(attrs={
				'class': 'input-text',
				'id': 'policy-number',
			}),
			"registration_number": forms.TextInput(attrs={
				'class': 'input-text',
				'id': 'registration-number',
			}),
			
			"start_date": forms.TextInput(attrs={
				'type': 'date', 'class': 'input-date',
				'id': 'start-date',
			}),
			"end_date": forms.TextInput(attrs={
				'type': 'date', 'class': 'input-date', 'id': 'end-date',
			}),
			"renewal_date": forms.TextInput(attrs={
				'type': 'date', 'class': 'input-date', 'id': 'renewal-date',
			}),
			"amount": forms.TextInput(attrs={
				'class': 'input-text', 'id': 'amount',
			}),
			"created_by": forms.TextInput(attrs={
				'class': 'input-text', 'placeholder': 'Amount', 'id': 'amount',
			}),
			"phone_number": forms.TextInput(attrs={
				'class': 'input-text',
				'id': 'phone-number',
			}),
		}


class SearchForm(forms.Form):
	CATEGORY_CHOICES = [
		('name', 'Name'),
		('policy_number', 'Policy Number'),
		('registration_number', 'Registration Number'),
	]
	category = forms.ChoiceField(choices=CATEGORY_CHOICES, required=True)
	query = forms.CharField(max_length=50, required=True, min_length=1,
		widget=forms.TextInput(attrs={
			'class': 'query', 'id': 'query', 'placeholder': 'query'
		}))


class EditClient(forms.ModelForm):
	class Meta:
		model = Client
		fields = '__all__'

clients/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Client
from .forms import ClientForm, SearchForm, EditClient
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

  
# @login_required
def index(request):
	clients = Client.objects.all().order_by("renewal_date")
	print(clients)
	clients = Client.objects.filter(created_by=request.user).order_by("renewal_date")
	return render(request, "clients/index.html", {
		"clients": clients
	})


# @login_required
def register(request):
	if request.method == "POST":
		form = ClientForm(request.POST)
		# print(form.created_by)
		if form.is_valid():
			client = form.save(commit=False)
			client.created_by = request.user
			client.save()
			return HttpResponseRedirect(reverse('clients:register'))
		else:
			print(form.cleaned_data, request.user)
			return render(request, "clients/register.html", {
				"message": "error: failed to add client"
			})
	else:
		form = ClientForm()
		return render(request, "clients/register.html", {
			"form": form
		})


# @login_required
def search_view(request):
	form = SearchForm(request.GET or None)
	results = []
	message = [' ']
	if request.method == 'GET' and form.is_valid():
			category = form.cleaned_data['category']
			query = form.cleaned_data['query']
			results = search(request, category, query)
			print(len(results))
	else:
		try:
			query_lenth = len(form.cleaned_data['query'])
		except (AttributeError, KeyError):
			return render(request, 'clients/search.html',
				{'form': form, 'results': results,}
			)
	if len(results) == 0:
		message[0] = 'client not found: review search query and try again'

	print(results)
	return render(request, 'clients/search.html', 
			   {'form': form, 'results': results, 'message': message[0],}
			   )

def search(request, category, query):
	search_filters = {
		'name': {'name__icontains': query},
		'registration_number': {'registration_number__icontains': query},
		'policy_number': {'policy_number__icontains': query},
		'created_by': {'created_by': request.user}
	}

	filter_kwargs = search_filters.get(category, {})
	results = Client.objects.filter(**filter_kwargs) if filter_kwargs else message

	return results


# @login_required
def client_details(request, client_id):
	client = Client.objects.filter(id=client_id, created_by=request.user) if client_id else None
	return render(request, 'clients/client_details.html', {'client': client})


# @login_required
def edit_client(request, client_id):
	client = get_object_or_404(Client, id=client_id, created_by=request.user)
	if request.method == 'POST':
		form = EditClient(request.POST, instance=client)
		if form.is_valid():
			print('is valid')
			form.save()
			return redirect('clients:index')
	else:
		form = ClientForm(instance=client)
	return render(request, 'clients/edit.html',
		{'form': form, 'client': client,

	})


# @login_required
def delete_client(request, pk):
	client = get_object_or_404(Client, pk=pk, created_by=request.user)
	if request.method == 'POST':
		client.delete()
		messages.success(request, "The client was deleted successfully.")
		return redirect('clients:index')
	return render(request, 'clients/edit.html', {'client': client})

clients/templates/clients/client_details.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Title</title>
</head>
<body>
	{{ client}}
</body>
</html>

clients/templates/clients/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	{% load static %}
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'clients/index.css' %}">
	<title>Delete</title>
</head>
<body>
	<form method="post" class="card" action="{% url 'delete' client.id %}">
      {% csrf_token %}
      <h2>Delete Client</h2>
      <p>Are you sure you want to delete {{ client.name }}?</p>
      <p class="form-buttons">
        <input type="submit" class="btn btn-primary" value="Delete">
        <a href="{% url 'index' %}" class="btn btn-outline">Cancel</a>
      </p>
    </form>
</body>
</html>

clients/templates/clients/edit.html
{% extends 'clients/index.html' %}

{% load static %}

{% block extra_css %}
	<link rel="stylesheet" href="{% static 'clients/edit.css' %}">

{% endblock %}

{% block title %}Edit Client{% endblock %}

{% block body %}

<br>
<br>
<br>
<section id="edit-wrapper">
<h1 class="title">Edit Client</h1>
<br>
<form id="edit_form" method="POST" action="{% url 'clients:edit_client' client.id %}">
	{% csrf_token %}
	<div class="form-element">
		<label>Name**<br>
			{{ form.name }}
		</label>
	</div>
	<div class="form-element">
		<label>Reg No.**<br>
			{{ form.registration_number }}
		</label>
	</div>
	<div class="form-element">
		<label>Policy No**.<br>
			{{ form.policy_number }}
		</label>
	</div>
	<div class="form-element">
		<label>Phone No**.<br>
			{{ form.phone_number }}
		</label>
	</div>
	<div class="form-element">
		<label class="date-label">Start Date**<br>
			{{ form.start_date }}
		</label>
	</div>
	<div class="form-element">
		<label class="date-label">End Date<br>
			{{ form.end_date }}
		</label>
	</div>
	<div class="form-element">
		<label class="date-label">
			<span>Renewal Date</span>
			{{ form.renewal_date }}
		</label>
	</div>
	<div class="form-element">
		<label>Amount**<br>
			{{ form.amount }}
		</label>
	</div>
	<div id="save-wrapper">
		<label>
			<input id="save" class="submit" type="submit" value="Save">
		</label>
	</div>

</form>
<form id="delete" action="{% url 'clients:delete' client.id %}" method="POST">
	 {% csrf_token %}
	<input class="delete" type="submit" value="Delete">
</form>
</section>
{% endblock %}

clients/templates/clients/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load static %}
	<meta charset="UTF-8">
	<link rel="icon" type="image/png" href="{% static 'iconfavicon.png' %}">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{% load static %}
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<link href="{% static 'manifest.json' %}" rel="manifest">
	<script defer src="{% static 'js/main.js' %}"></script>
	<link rel="stylesheet" href="{% static 'clients/index.css' %}">
	<link rel="stylesheet" href="{% static 'clients/mediaindex.css' %}">
	{% block extra_css %}{% endblock %}
	<script defer src="{% static 'clients/index.js' %}"></script>
	<title>{% block title %} Clients {% endblock %}</title>
</head>
<body>
<nav>
	<div>
		<form id="home" action="{% url 'eccentric:home' %}">
			{% csrf_token %}
			<button class="title home" type="submit">Sinsio</button>
		</form>
	</div>
	<form action="{% url 'eccentric:logout' %}" method="POST">
		{% csrf_token %}
		<input class="logout" type="submit" value="Logout">
	</form>
</nav>
{% block body %}
<br>
<br>
<br>
<section id="clients">
	<div class="clients-wrapper">
		<div class="column-title">
			<div class="title">ClIENT NAME</div>
			<div class="title">RENEWAL DATE</div>
		</div>
		<div>
			{% if not clients %}
			<p style="font-size: 16px">Add Your First Client</p>
			{% endif %}
		</div>
		<div class="all-clients">
			{% for client in clients %}
			<form class="client" action="{% url 'clients:edit_client' client.id %}" method="get">
				{% csrf_token %}
				<div class="client-heading">
					<div class="client-name">{{ client.name }}</div>
					<div class="renewal-date">{{ client.renewal_date }}</div>
				</div>
				<div class="amount-wrapper">
					<div class="client-amount">
						KES: {{ client.amount }}
					</div>
					<div class="more">
						<img class="triangle-svg" src="{% static 'clients/svg/triangle_down.svg' %}">
					</div>
				</div>
				<div class="all-details" style="display: none">
					<label class="client-detail"> Registration Number:
						<span>{{ client.registration_number }}</span>
					</label>
					<label class="client-detail"> Policy Number:
						<span>{{ client.policy_number }}</span>
					</label>
					<label class="client-detail"> Renewal Date:
						<span>{{ client.renewal_date }}</span>
					</label>
					<label class="client-detail"> Start Date:
						<span>{{ client.start_date }}</span>
					</label>
					<label class="client-detail"> End Date:
						<span>{{ client.end_date }}</span>
					</label>
					
					<label class="client-detail"> Phone No:
						<span>{{ client.phone_number }}</span>
					</label>
					<button type="submit" class="edit-button">Edit</button>
				</div>
			</form>
			{% endfor %}
		</div>
	</div>
</section>
{% endblock %}
<form class="add-client" action="{% url 'clients:register' %}">
	<button id="add-client"><span>+</span></button>
</form>
<footer>
		<form action="{% url 'clients:index' %}" method="POST">
			{% csrf_token %}
			<button type="submit" class="clients">
				<img id="clients-group" src="{% static 'eccentric/svg/clients_group.svg' %}">
			</button>
		</form>

		<form action="{% url 'clients:search' %}" method="POST">
			{% csrf_token %}
			<button type="submit" class="search">
				<img id="search-client" src="{% static 'eccentric/svg/search.svg' %}">
			</button>
		</form>

		<button class="notify">
			<img id="notify" src="{% static 'eccentric/svg/notify.svg' %}">
		</button>
	</footer>
</body>
</html>

clients/templates/clients/loggedin.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	{% load static %}
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'clients/index.css' %}">
	<script defer src="{% static 'clients/index.js' %}"></script>
	<title>Logged In</title>
</head>
<body>
<nav>
	<div class="profile">
		<form action="{% url 'eccentric:logout' %}">
			<button type="submit" class="profile">Profile</button>
		</form>
	</div>
	<div class="logo">
		Eccentric Suit
	</div>
	<div class="logout">
		<form action="{% url 'eccentric:logout' %}">
			<button type="submit" id="logout">Log Out</button>
		</form>
	</div>
</nav>
<section id="section-search" style="display: none">
	<div class="search-wrapper">
		<form id="search-form" action="{% url 'clients:search'  %}">
			{% csrf_token %}
			<div class="seach-by sf-element">
				<select name="search-by" class="sf-element">
					<option>Name</option>
					<option>Reg Number</option>
					<option>Policy Number</option>
					<option>Start Date</option>
				</select>
			</div>
			<div>
				<input name="query" id="search-value" class="seach-input sf-element" type="text" placeholder="Type">
				</input>
			</div>
			<div>
				<button type="submit" id="search-button" class="sf-element">Search</button>
			</div>
		</form>
	</div>
</section>
{% block body %}
{% endblock %}
<form class="add-client" action="{% url 'clients:register' %}">
	<button id="add-client">+</button>
</form>
<footer>
	<button class="clients">
		Clients
	</button>
	<button class="search-button">
		Search
	</button>
	<button class="reminder">
		<a>Reminders</a>
	</button>
</footer>
</body>
</html>

clients/templates/clients/register.html
{% extends 'clients/index.html' %}

{% load static %}

{% block extra_css %}
	<link rel="stylesheet" href="{% static 'clients/register.css' %}">
{% endblock %}

{% block title %}Add Clients{% endblock %}

{% block body %}
<br>
<br>
<br>
<section id="client">
	<div class="client-wrapper">
		<div class="title">
			Client Details
		</div>
		<br>
		<div class="form-container">
			<form id="registration-form" action="{% url 'clients:register' %}" method="POST">
				{% csrf_token %}
				<div class="form-element">
					<label>Name**<br>
						{{ form.name }}
					</label>
				</div>
				<div class="form-element">
					<label>Reg No.**<br>
						{{ form.registration_number }}
					</label>
				</div>
				<div class="form-element">
					<label>Policy No**.<br>
						{{ form.policy_number }}
					</label>
				</div>
				<br>
				<div class="form-element">
					<label class="date-label">Start Date**<br>
						{{ form.start_date }}
					</label>
				</div>
				<div class="form-element">
					<label class="date-label">End Date<br>
						{{ form.end_date }}
					</label>
				</div>
				<div class="form-element">
					<label class="date-label">
						<span>Renewal Date</span>
						{{ form.renewal_date }}
					</label>
				</div>
				<div class="form-element">
					<label>Amount**<br>
						{{ form.amount }}
					</label>
				</div>
				<div class="form-element"  id="add-wrapper">
					<label>
						<input id="add" class="submit" type="submit" value="Add">
					</label>
				</div>
			</form>
			<br>
			<form action="{% url 'clients:index' %}">
				<label>
					<input id="done" class="submit" type="submit" value="Done">
				</label>
			</form>
			<div class="message">
			</div>
		</div>
	</div>
</section>
{% endblock %}

clients/templates/clients/search.html
{% extends 'clients/index.html' %}

{% load static %}

{% block extra_css %}
	<link rel="stylesheet" href="{% static 'clients/search.css' %}">
{% endblock %}

{% block title %}Search{% endblock %}

{% block body %}
<br>
<br>
<br>
<section id="section-search">
	<div class="search-wrapper">
		<form id="search-form" action="{% url 'clients:search' %}">
			<div class="search-by sf-element">
				<div class="category">{{ form.category }}</div>
				<div id="query">{{ form.query }}</div>
			</div>
			<div>
				<button type="submit" id="search-button" >Search</button>
			</div>
		</form>
	</div>
</section>
<br>
<section id="clients">
	<div class="clients-wrapper">
		<div class="title">
			Clients Details
		</div>
		<div class="all-clients">
			{% for client in results %}
				<form class="client" action="{% url 'clients:edit_client' client.id %}" method="get">
				<div class="client-heading">
					<div class="client-name">{{ client.name }}</div>
					<div class="renewal-date">{{ client.renewal_date }}</div>
				</div>
				<div class="amount-wrapper">
					<div class="client-amount">
						KES: {{ client.amount }}
					</div>
					<div class="more">
						<img class="triangle-svg" src="{% static 'clients/svg/triangle_down.svg' %}">
					</div>
				</div>
				<div class="all-details" style="display: none">
					<label class="client-detail"> Registration Number:
						<span>{{ client.registration_number }}</span>
					</label>
					<label class="client-detail"> Policy Number:
						<span>{{ client.policy_number }}</span>
					</label>
					<label class="client-detail"> Phone Number:
						<span>{{ client.phone_number }}</span>
					</label>
					<label class="client-detail"> Start Date:
						<span>{{ client.start_date }}</span>
					</label>
					<label class="client-detail"> End Date:
						<span>{{ client.end_date }}</span>
					</label>
					<label class="client-detail"> Renewal Date:
						<span>{{ client.renewal_date }}</span>
					</label>
					<button type="submit" class="edit-button">Edit</button>
				</div>

			</form>
			{% endfor %}
			{% if message %}
				<h1 style="color: red;">{{ message}}</h1>
			{% endif %}
		</div>
	</div>
</section>
{% endblock %}